### YamlMime:ModuleUnit
uid: learn.introduction-to-github-copilot.when-to-use-{product}
title: When to use {product}
metadata:
  title: when-to-use-{product}
  description: "TODO this field is for search engine optimization and is not user-visible; use 2-3 complete, grammatically correct sentences to describe the unit; include relevant search keywords."
  ms.date: 2/6/2023
  author: a-a-ron
  ms.author: aastewar
  ms.topic: interactive-tutorial
  ms.prod: learning-azure # Edit as appropriate for your portfolio area
durationInMinutes: 7
content: |
  [!include[](includes/4-when-to-use-{product}.md)]
