### YamlMime:ModuleUnit
uid: learn.configure-dependabot-security-updates-on-github-repo.introduction
title: Introduction
metadata:
  unitType: introduction
  title: Introduction
  description: GitHub dependency management tools help you handle the security risks and maintenance requirements of incorporating third-party software into your project.
  ms.date: 08/28/2022
  author: sterling463
  ms.author: csterling 
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 1
content: |
  [!include[](includes/1-introduction.md)]
